name: Build FlexClient

on:
  push:
    branches: [ "26.1.2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: FlexClient
          path: build/libs/*-dev.jar
